### ISSUE TITLE
Add Balance to Get Miner Permission Tree

### ISSUE THREAD

**Issue by joeblau** [0L-Analytics/permission-tree-monitoring#2]
Is there a way to add the balance to miner permission tree endpoint?

```typescript
interface PermissionNodeMiner { 
  ...
  balance: number
}
```

**Comment by agouin** [comment]
Since this information is volatile, I'd recommend fetching it from the diem-node json-rpc directly: https://github.com/0LNetworkCommunity/libra/blob/main/json-rpc/docs/method_get_account.md
